export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with zero fees",
  description:
    "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/planet.png"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimited Access",
  headline: "Log In",
  description: "all you need is an internet connection and a phone or computer",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/planet.png"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Join Our Team",
  headline: "Creating your account is very easy.",
  description: "Set Up",
  buttonLabel: "Start Now",
  imgStart: false,
  img: require("../../images/planet.png"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
